version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "friday"
          time: "09:00"
          timezone: "America/Los_Angeles"
      groups:
          dev-dependencies:
              dependency-type: "development"
              exclude-patterns:
                  - "*storybook*"
                  - "*electron*"
          storybook:
              patterns:
                  - "*storybook*"
          prod-dependencies:
              dependency-type: "production"
              exclude-patterns:
                  - "*electron*"
                  - "jotai"
          electron:
              patterns:
                  - "*electron*"
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "friday"
          time: "09:00"
          timezone: "America/Los_Angeles"
    - package-ecosystem: "github-actions"
      directory: "/.github/workflows"
      schedule:
          interval: "weekly"
          day: "friday"
          time: "09:00"
          timezone: "America/Los_Angeles"
