version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      groups:
          dev-dependencies:
              dependency-type: "development"
              exclude-patterns:
                  - "@storybook/*"
                  - "*electron*"
          storybook:
              patterns:
                  - "@storybook/*"
          prod-dependencies:
              dependency-type: "production"
              exclude-patterns:
                  - "*electron*"
          electron:
              patterns:
                  - "*electron*"
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "github-actions"
      directory: "/.github/workflows"
      schedule:
          interval: "daily"
