version: "3"

vars:
    APP_NAME: "NextWave"
    BIN_DIR: "bin"
    VERSION: "0.1.0"


tasks:
    generate:
        cmds:
            - go run cmd/generate/main-generate.go
        sources:
            - "cmd/generate/*.go"
            - "pkg/service/**/*.go"
            - "pkg/wstore/*.go"

    webpack:
        cmds:
            - yarn run webpack --watch --env dev

    electron:
        cmds:
            - WAVETERM_DEV=1 yarn run electron dist-dev/emain.js
        deps:
            - build:server

    build:server:
        cmds:
            - go build -o bin/wavesrv cmd/server/main-server.go
        sources:
            - "cmd/server/*.go"
            - "pkg/**/*.go"
        generates:
            - bin/wavesrv
        deps:
            - go:mod:tidy

    go:mod:tidy:
        summary: Runs `go mod tidy`
        internal: true
        generates:
            - go.sum
        sources:
            - go.mod
        cmds:
            - go mod tidy


