name: Bug Report
description: Create a bug report to help us improve.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
    - type: textarea
      attributes:
          label: Current Behavior
          description: A concise description of what you're experiencing.
      validations:
          required: false
    - type: textarea
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: false
    - type: textarea
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. In this environment...
              1. With this config...
              1. Run '...'
              1. See error...
      validations:
          required: false
    - type: textarea
      attributes:
          label: Environment
          description: |
              examples:
                - **OS**: Ubuntu 20.04
                - **Architecture**: arm64
                - **Wave Version**: v0.8.8
          value: |
              - OS:
              - Architecture:
              - Wave Version:
          render: markdown
      validations:
          required: false
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
    - type: checkboxes
      attributes:
          label: Questionnaire
          description: "If you feel up to the challenge, please check one of the boxes below:"
          options:
              - label: I'm interested in fixing this myself but don't know where to start
                required: false
              - label: I would like to fix and I have a solution
                required: false
              - label: I don't have time to fix this right now, but maybe later
                required: false
