# AI提示词优化程序 - 极简配置示例

# 方案一：使用OneAPI网关（推荐）
model_providers:
  oneapi:
    api_base: "https://api.trustoken.cn/v1"  # 你的OneAPI地址
    api_key: "sk-your-token-here"            # 你的API密钥
    models: ["auto"]                         # auto表示使用网关的默认模型
    default_model: "auto"
    enabled: true

# 方案二：直连OpenAI
# model_providers:
#   openai:
#     api_base: "https://api.openai.com/v1"
#     api_key: "sk-your-openai-key"
#     models: ["gpt-4", "gpt-3.5-turbo"]
#     default_model: "gpt-4"
#     enabled: true

# 基础配置
ai_models:
  default_provider: "oneapi"
  timeout: 600

# 可选配置
plugins:
  temperature: 0.7
  max_tokens: 4000 